simsy_cms_controllers:
    resource:
        path: ../../Controller/
        namespace: Smoq\SimsyCMS\Controller
    type: attribute

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"