services:
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Smoq\SimsyCMS\:
        resource: "../../"
        exclude:
            - "../../DependencyInjection/"
            - "../../Resources/"
            - "../../Tests/"

    Smoq\SimsyCMS\Listener\EntityTablePrefixerListener:
        arguments:
            $prefix: 'simsy_cms_'

    Smoq\SimsyCMS\Listener\BlockDiscriminatoryMapListener:
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }